### ISSUE TITLE
1° requisito funcional com as especificações das regras de negócio necessárias para a implementação do processo.

### ISSUE THREAD

**Issue by mariana2903** [Inteli-College/2024-T0002-EC09-G02#16]
Os requisitos deverão ser escritos em arquivo markdown e disponibilizados como documentação funcional do projeto no repositório git do grupo. O Requisito funcional deverá contemplar os seguintes tópicos:
a) Título - Nome significativo para o requisito.
b) Descrição detalhada do processo a ser digitalizado - Explicação clara e completa do processo a ser automatizado.
c) Descrição do fluxo principal - Detalhes do fluxo principal do processo, incluindo passos e ações envolvidas.
d) Descrição do fluxo alternativo - Descrição dos possíveis fluxos alternativos que podem ocorrer no processo.
e) Descrição do fluxo de exceção - Detalhamento dos cenários de exceção que podem surgir e como o sistema deve lidar com eles. PADRÃO DE QUALIDADE:

**Comment by gustavofdeoliveira** [comment]
@mariana2903 tu acabou criando no projeto errado a issue
