### ISSUE TITLE
Análise financeira do projeto

### ISSUE THREAD

**Issue by gustavofdeoliveira** [Inteli-College/2024-T0002-EC09-G02#6]
Deve ser informado o quanto o parceiro tem projetado para investir no projeto e quais são as projeções de custos e de receitas que o parceiro projeta ter relacionadas ao projeto (para o período de um ano). Ressalta-se que é uma estimativa. Caso o projeto seja interno, não existindo vendas (receita), não é necessário informar a receita estimada. Para que a entrega seja realizada, basta informar esses dados e a lógica que o parceiro forneceu para alcançá-los. 

Link para os templates: 
https://drive.google.com/drive/u/3/folders/1lTqisJ_gxxtc5J5aXM8ula2kQ4MsII_M

Formato da entrega:
O envio deve ser disponibilizado em PDF no Github do grupo, dentro do diretório "Documentos"

**Comment by joaocarazzato** [comment]
https://github.com/Inteli-College/2024-T0002-EC09-G02/commit/57c0556bb65c5e023f656e9bcbd4670d2936ff1a
