### ISSUE TITLE
Jornada do Usuário

### ISSUE THREAD

**Issue by gustavofdeoliveira** [Inteli-College/2024-T0002-EC09-G02#7]
@joaocarazzato @Lukovsk 

Layout de mapa de jornada do usuário utilizando um template:

- Ambiente Urbano: Contextualizar o ambiente da cidade, como bairros centrais, subúrbios, favelas ou áreas comerciais.
- Início da Jornada: Descrição clara do ponto de partida, como o reconhecimento de uma necessidade ou o primeiro contato com o sistema ou serviço.
- Etapa de Interação: Cada ponto de contato ou interação que o usuário tem com o serviço ou produto. Isso pode ser subdividido em:
- Fases da Jornada: Dividido em etapas, como conscientização, consideração, decisão, uso e defesa.
- Ações: O que o usuário está fazendo em cada etapa.
- Pensamentos: O que o usuário pode estar pensando durante cada ação ou interação.
- Sentimentos: O estado emocional do usuário, que pode ser positivo, neutro ou negativo.
- Oportunidades: Identificação de áreas de melhoria ou otimização.
- Interação com Tecnologias Urbanas: Como a persona interage com soluções de cidade inteligente, como sensores, aplicativos de mobilidade, soluções de energia renovável, entre outros.
- Interações Sociais e Espaciais: Como a persona se move e interage no espaço urbano.
- Touchpoints: Canais ou pontos onde ocorre a interação, como site, aplicativo, atendimento ao cliente, loja física, etc.
- Picos e Vales: Destacar os principais pontos de satisfação (picos) e de frustração (vales) ao longo da jornada.
- Final da Jornada: Descrição clara do desfecho da jornada, como a solução de um problema, a compra de um produto ou a conclusão de uma tarefa.
- Feedbacks e Insights em Contexto Urbano: Quais são os desafios específicos relacionados ao ambiente de cidade inteligente? Há barreiras tecnológicas, sociais ou físicas que dificultam a jornada?
- Múltiplas Personas: Caso opte por esse formato, o aluno deve representar diferentes personas e suas respectivas jornadas no mesmo mapa. Isso mostrará como diferentes segmentos da população interagem com soluções urbanas inteligentes, revelando pontos de interseção e áreas de potencial conflito ou colaboração.

**Comment by joaocarazzato** [comment]
https://github.com/Inteli-College/2024-T0002-EC09-G02/commit/87be691be762b17c25b1837c25d3ca2209e2dddd
